functions:
  getPayments:
    handler: src/handlers.getPayments
    events:
      - http:
          path: /v1/payments
          method: get
          cors: true
  getPaymentById:
    handler: src/handlers.getPaymentById
    events:
      - http:
          path: /v1/payments/{paymentId}
          method: get
          cors: true
  getPaymentsByUserId:
    handler: src/handlers.getPaymentsByUserId
    events:
      - http:
          path: /v1/payments/user/{userId}
          method: get
          cors: true
          request:
            template:
              application/json: >
                {
                  "status" : "$input.params('status')"
                }
  createPayment:
    handler: src/handlers.createPayment
    events:
      - http:
          path: /v1/payments
          method: post
          cors: true
  updatePayment:
    handler: src/handlers.updatePayment
    events:
      - http:
          path: /v1/payments
          method: put
          cors: true
  deletePayment:
    handler: src/handlers.deletePayment
    events:
      - http:
          path: /v1/payments/{paymentId}
          method: delete
          cors: true
